### ISSUE TITLE
Краш java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

### ISSUE THREAD

**Issue by EduardAblekimov** [yandexmobile/metrica-plugin-xamarin#19]
Крашится со следующей ошибкой:

```
10-25 13:10:53.427 18480 18512 I AppMetrica: [my.package.name] : [] Initializing of Metrica, Release type, Version 3.6.4, API Level 81, Dated 13.06.2019.
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient: Error while reading from SharedPreferences
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.app.ContextImpl.checkMode(ContextImpl.java:2495)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:414)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:404)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:12)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at java.lang.reflect.Method.invoke(Native Method)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at com.yandex.metrica.impl.ac.GoogleAdvertisingIdGetter.e(SourceFile:261)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at com.yandex.metrica.impl.ac.GoogleAdvertisingIdGetter.b(SourceFile:51)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at com.yandex.metrica.impl.ac.GoogleAdvertisingIdGetter$2.a(SourceFile:163)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at com.yandex.metrica.impl.ac.GoogleAdvertisingIdGetter$2.call(SourceFile:158)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.os.Handler.handleCallback(Handler.java:873)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.os.Handler.dispatchMessage(Handler.java:99)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.os.Looper.loop(Looper.java:193)
10-25 13:10:53.453 18480 18509 W AdvertisingIdClient:   at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by EduardAblekimov** [comment]
Вроде бы нужно обновить либу с 3.6.4 на 3.8.0, но я не уверен исправлен ли там этот баг.

**Comment by NesterovichAlexey** [comment]
Привет. Извини за долгий ответ. Этот крэш уже исправлен в версии 3.7.2. Но лучше сразу обновлять на 3.8.0

**Comment by EduardAblekimov** [comment]
@NesterovichAlexey а нугеты (и текущий репо) будут обновляться или надо вручную это сделать?

**Comment by NesterovichAlexey** [comment]
Если надо прямо сейчас, то лучше обновить вручную.
Нугеты (и текущий репо) будут обновлены чуть позднее.
